apiVersion: apps/v1
kind: Deployment
metadata:
  name: %ENVIRONMENT%-%APP_NAME%-deployment
  namespace: %NAMESPACE% 
spec:
  selector:
    matchLabels:
      app: %ENVIRONMENT%-%APP_NAME%
  replicas: %REPLICAS%
  template:
    metadata:
      labels:
        app: %ENVIRONMENT%-%APP_NAME%
    spec:
      containers:
      - name: %ENVIRONMENT%-%APP_NAME%
        image: "%DOCKER_REGISTRY%%REPO%:latest"
        ports:
        - containerPort: %CONTAINER_PORT%
---
kind: Service
apiVersion: v1
metadata:
  name: %ENVIRONMENT%-%APP_NAME%-svc
  namespace: %NAMESPACE% 
spec:
  selector:
    app: %ENVIRONMENT%-%APP_NAME%
  ports:
  - port: %HOST_PORT%
  externalIPs:
    - %HOST_IP%
  type: LoadBalancer #ClusterIP # LoadBalancer # NodePort # 